[package]
name = "rustask_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "=4.8.0"
dotenv = "0.15.0"
futures = "0.3.31"
mongodb = "3.4.1"
serde = "1.0.228"
tracing = "0.1.43"
tracing-actix-web = "0.7.19"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
